export enum HcloudErrorCode {
    Forbidden = 'forbidden',
    Unauthorized = 'unauthorized',
    InvalidInput = 'invalid_input',
    JsonError = 'json_error',
    Locked = 'locked',
    NotFound = 'not_found',
    RateLimitExceeded = 'rate_limit_exceeded',
    ResourceLimitExceeded = 'resource_limit_exceeded',
    ResourceUnavailable = 'resource_unavailable',
    ServerError = 'server_error',
    ServiceError = 'service_error',
    UniquenessError = 'uniqueness_error',
    Protected = 'protected',
    Maintenance = 'maintenance',
    Conflict = 'conflict',
    UnsupportedError = 'unsupported_error',
    TokenReadonly = 'token_readonly',
    Unavailable = 'unavailable',
    DeprecatedApiEndpoint = 'deprecated_api_endpoint',
}